services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "/volumes/postgresql/data:/var/lib/postgresql/data"
      - "/volumes/postgresql/init:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: hornet